### ISSUE TITLE
Oops this lab was made into a readme

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/map-state-to-props-lab#1]
@aturkewi @Lukeghenco 

There's a button to finish reading instead of a fork / pass test / pull request light.

**Comment by Enoch2k2** [comment]
Update to the above issue - just checked out the full stack with react and it's a lab in that track. Is the expert track and the full stack react track so different and should we be doing this in the full stack react track instead?

**Comment by aturkewi** [comment]
If this is showing up correctly in `v-000`, I'm going to close this ticket. If you run into this again @Enoch2k2 please just let me know which batch and track you're seeing the issue in. 

As a Learn Expert, I would say the best place to work on your react and redux would be in the new full stack track :) That way you'll be seeing exactly what the students will be seeing!
