### ISSUE TITLE
UserInput.js explanation doesn't match up with code given

### ISSUE THREAD

**Issue by kostanzhoglo** [learn-co-curriculum/map-state-to-props-lab#11]
The 2nd and 3rd paragraphs in the section **Test by Dispatching an Action** discuss the file UserInput.js.

The text in the ReadMe doesn't match up with what is given in the file UserInput.js itself.

Learning MapStateTopProps and Connect() is difficult to understand at first, but seeing code that doesn't exist be explained is especially weird.

Please fix this section.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have updated the materials, made sure that the README reflects what is in UserInput.js and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
