### ISSUE TITLE
Bug in test code

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/map-state-to-props-lab#13]
The last test can be defeated if you render the users name and hometown with an `<h3>` and `<h4>` tag since the test is just looking for a `3` and then a `4` in the HTML somewhere. 

An easy fix for the test would be to put more names in state than there are header tags.

**Comment by maxwellbenton** [comment]
Hey @micahshute,

Thanks for this feedback and for the suggested fix. I've gone ahead and used your suggestion, adding more names to state to prevent a false positive due to an `<h3>` and `<h4>`.

Thank you!
