### ISSUE TITLE
The comments on where to add code are not consistent

### ISSUE THREAD

**Issue by jenniferbusca** [learn-co-curriculum/map-state-to-props-lab#14]
In some places there are comments to add code, however it's not in all of the places necessary to get the tests to pass. There should be comments in all places where additional code is needed or not at all. It's confusing that only some are commented.

**Comment by maxwellbenton** [comment]
Hi @jenniferbusca,

Thank you for opening this issue. We're in the process of updating our React materials and have updated this lab based on your feedback, adding additional comments in the starter code in every place where code is needed to provide better guidance to students, which should resolve this issue.

We apologize for any confusion or frustration this may have caused you, but we appreciate you taking the time to provide feedback and help improve our curriculum!

Thank you!
