### ISSUE TITLE
this lesson is too confusing, there is not enough guidance

### ISSUE THREAD

**Issue by ldgarber** [learn-co-curriculum/map-state-to-props-lab#2]

**Comment by maxwellbenton** [comment]
Thank you for spotting these issues and providing feedback.

We have updated the materials for this lesson, rewrote the readme and tests to help clarify concepts and believe your issues to be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
