### ISSUE TITLE
Misleading lesson

### ISSUE THREAD

**Issue by gloverab** [learn-co-curriculum/map-state-to-props-lab#3]
I saw one other person open an issue that there is not enough guidance in this lesson. I agree, and I'd like to elaborate a bit.

One of the most misleading things (other than it having a totally different file tree than the instructional lab before it) about this lesson is that when you open it up, portions of the code have curly brackets with comments inside them (ex. `{/* stuff should happen around here */}`). Since curly brackets are a big part of React, this registers as "okay, I should be putting code inside these curly brackets." However, this is not the case! The curly brackets need to be removed altogether, but we have no way of knowing that.

My suggestion would be removing the comments from the lab itself, and having a more informative Readme (i.e. the other labs in this course), because it makes little sense to have it set up this way.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have updated the materials for this lesson, rewrote the readme and tests to help clarify concepts and believe your issues to be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
