### ISSUE TITLE
New syntax introduced?

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/map-state-to-props-lab#4]
I had trouble figuring out what to do with `export const ConnectedUsers = Users`. I don't think it was covered in a prior lesson.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials for this lesson, rewrote the readme, starter code and tests and removed this line.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
