### ISSUE TITLE
I want to echo sentiments that this is a confusing lab

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/map-state-to-props-lab#5]
The readme before this lab tells the readers that using connect and mapStateToProps is a little hard to wrap one's head around and does not give much explanation as to how it works. It is a little frustrating to then be presented with a lab without more explanation as to what is going on. I think that explaining a little more how writing a mapStateToProps function works and what it returns would be very helpful. I understand that a great way to learn is to synthesize a solution from previous information, but it felt as though we weren't given enough information to synthesize from. Also, the comments in the curly braces did more harm than good.

**Comment by maxwellbenton** [comment]
Thank you for spotting these issues and providing feedback.

We have updated the materials for this lesson, rewrote the readme and tests to help clarify concepts and believe your issues to be resolved.

We apologize for any frustration you have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
