### ISSUE TITLE
this lab doesn't has unnecessarily confusing differences relative to the readme

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/map-state-to-props-lab#6]
I can't get a single test to pass even though the store appears to be updating and logging my state updates to the screen.

I don't know if my code is running as is expected for the tests so I looked up the answer and had a few questions based on the code shown.

In App.js

Before starting, why does it say    {/* is there something we could connect to here? */} in curly brackets? Based on previous lessons, I knew that we needed to enter a Component here but we were not taught to enter a component in with {brackets around it} so it threw me off as I didn't think a Component wrapped in brackets was syntax that was going to work and it does.

In Users.js
Naming the exported component "ConnectedUsers" was very confusing as the readme shows a default export of the connect method in which we use a MapStateToProps method with and a Component that has the same name as the file. However your answer uses a named export instead and makes things much more confusing.

The whole time in App.js, i'm expecting to export a "Users" Component but the answer shows you export "ConnectedUsers."  

I feel like the name change of the Component to a named export const was unnecessary and adds confusion since this was not done in the readme and if I recall, none of the lessons prior.

Here is the code I used which works in the browser but fails all tests. The overall code changes needed to make this lab work are subtle but I feel as though the comments within the labs and the Component name change in Users.js add a lot more confusion to this lab than there needs to be.  You never talk about named exports in this course and you always default export in readme's and labs so to randomly spring it here in this lab lesson with no explanation is insane.
 

`

App.js
import React, { Component } from 'react';
import UserInput from './components/UserInput'
import Users from './components/Users'

export class App extends Component {
  render() {
    return (
      <div className="App">
        <UserInput store={this.props.store}/>
        <Users />
      </div>
    );
  }
}

export default App;

Users.js
import React, { Component } from 'react';
import { connect } from 'react-redux';

export class Users extends Component {

  render() {
    let users = this.props.users.map((user, index) => <li key={index}>{user.userName}</li>);

    return (
      <div>
        <ul>
          {users}
        </ul>
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    users: state.users,
    primaryUser: state.users[0]
  };
};

export default connect(mapStateToProps)(Users)

`

**Comment by dkStephanos** [comment]
Seconded. This lab is put together terribly, introduces new topics with NO explanation, and the test failures offer almost zero direction. There should be additional lessons before hand or at MINIMUM a better set of instructions.

**Comment by maxwellbenton** [comment]
Thank you for spotting these issues and providing feedback.

We have updated the materials for this lesson, rewrote the readme and tests to help clarify concepts and believe your issues to be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
