### ISSUE TITLE
Some concepts should be clarified in readme before doing this lab

### ISSUE THREAD

**Issue by gb23** [learn-co-curriculum/map-state-to-props-lab#7]
I do not think mere mortals like myself have enough information beforehand to understand that `<ConnectedUsers />` can be called without any apparent props passed, yet have access to `this.props.users` within the Users class component.  Only after looking at the solution does it make sense that props are obtained through whatever is declared in the mapStateToProps method.  The readme discusses this, but without a concrete example, the discussion isn't solid.

Also, I'm all for 'getting the band back together', but the reducer file name should be changed from `manageBands.js` to `manageUsers.js`.

**Comment by dkStephanos** [comment]
Please address these issues!!

**Comment by maxwellbenton** [comment]
Thank you for spotting these issues and providing feedback.

We have updated the materials, rewrote the readme and tests to help clarify concepts and believe your issues to be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
