### ISSUE TITLE
Needs a rework

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/map-state-to-props-lab#8]
This lab has poor instruction, inconsistent structure and incorrectly named components. There are 6 open issues, none of which appear to be addressed. This is disappointing.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have updated the materials, rewrote the instructions and tests and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
