### ISSUE TITLE
Any reason we're using an ancient version of webpack here?

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-curriculum/map-state-to-props-lab#9]
Webpack has deprecated the docs for version 1.x. Any reason we're using that here in lieu of a newer version like 3 or 4?

We're not able to do this import here:

```
import ConnectedUsers from './Users'
```

when we've exported using 

```
export default connect(mapStateToProps)(Users)
```

I feel like that should have worked, but we needed to use destructuring instead.

**Comment by maxwellbenton** [comment]
Hey @DakotaLMartinez, I've updated webpack in all of the react and redux lessons to 3.x along with most of the other packages. webpack 4.x seems to cause problems with the existing set up of tests in most of our labs, so we'll have to stick with 3 until the next revision to react
